# Generated by Django 4.2 on 2023-04-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_region_cities_customuser_cities_customuser_regions"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.CharField(blank=True, max_length=1200),
        ),
    ]
