# Generated by Django 4.2 on 2023-04-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_customuser_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
    ]
