# Generated by Django 4.2 on 2023-04-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="phone_number",
            field=models.CharField(default="", max_length=14),
        ),
        migrations.AddField(
            model_name="item",
            name="shipping",
            field=models.BooleanField(default=False),
        ),
    ]
