# Generated by Django 4.2 on 2023-04-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_phone_number_item_shipping"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="supply_ability",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="item",
            name="supply_period",
            field=models.CharField(default="", max_length=255),
        ),
    ]
