# Generated by Django 4.2 on 2023-04-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_item_supply_ability_length_item_supply_ability_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="supply_ability",
            field=models.FloatField(),
        ),
    ]
