# Generated by Django 4.2 on 2023-04-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_item_supply_ability"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="payment_method",
            field=models.CharField(default="", max_length=255),
        ),
    ]
